spring:
  datasource:
    password: 3026606117
    username: root
    url: jdbc:mysql://localhost:3306/university
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update